/** @type {import('next').NextConfig} */

// --- Legacy WordPress URL → new site redirects ------------------------------
// Sourced from the old WordPress install: the Redirection plugin's enabled
// 301 rules plus the published post inventory. Keeps inbound links and search
// rankings intact after the WordPress → Next.js migration.

// Old top-level WordPress pages whose path changed on the new site.
const pageRedirects = [
  { source: "/contact-us", destination: "/contact", permanent: true },
  { source: "/business-loans", destination: "/financial-services", permanent: true },
  { source: "/new-business-loans", destination: "/financial-services", permanent: true },
  { source: "/business-loan/accounts-financing-new", destination: "/financial-services/accounts-receivable-financing", permanent: true },
  { source: "/business-loans/accounts-financing-new", destination: "/financial-services/accounts-receivable-financing", permanent: true },
  { source: "/industries", destination: "/", permanent: true },
  { source: "/subscribe", destination: "/contact", permanent: true },
  { source: "/terms-condition", destination: "/privacy-policy", permanent: true },
  { source: "/capital-markets", destination: "/financial-services", permanent: true },
  { source: "/category/business_loans", destination: "/financial-services", permanent: true },
  { source: "/sample-page", destination: "/", permanent: true },
];

// Industry & service pages restructured under /industries/ and
// /financial-services/ per the client's new URL specification. The old flat
// URLs were live and indexed, so each 301s to its new nested location.
const structureRedirects = [
  { source: "/business-services", destination: "/industries/business-services", permanent: true },
  { source: "/healthcare", destination: "/industries/healthcare-financing", permanent: true },
  { source: "/technology", destination: "/industries/technology-financing", permanent: true },
  { source: "/consumer-packaged", destination: "/industries/cpg-financing", permanent: true },
  { source: "/manufacturing", destination: "/industries/manufacturing-financing", permanent: true },
  { source: "/distribution-logistics", destination: "/industries/distribution-logistics-financing", permanent: true },
  { source: "/media-telecommunications", destination: "/industries/media-telecommunications-financing", permanent: true },
  { source: "/education-services", destination: "/industries/education-services", permanent: true },
  { source: "/government-contracting", destination: "/industries/government-contract-financing", permanent: true },
  { source: "/construction", destination: "/industries/commercial-construction-financing", permanent: true },
  { source: "/transportation-freight", destination: "/industries/transportation-freight-financing", permanent: true },
  { source: "/oil-gas", destination: "/industries/oil-gas-financing", permanent: true },
  { source: "/ar-financing", destination: "/financial-services/accounts-receivable-financing", permanent: true },
  { source: "/abl", destination: "/financial-services/asset-based-lending", permanent: true },
  { source: "/bridge", destination: "/financial-services/bridge-financing", permanent: true },
];

// Legacy WordPress service URLs under /business-loans/ → new service pages.
const legacyServiceRedirects = [
  { source: "/business-loans/accounts-receivable-financing", destination: "/financial-services/accounts-receivable-financing", permanent: true },
  { source: "/business-loans/purchase-order-financing", destination: "/financial-services/asset-based-lending", permanent: true },
  { source: "/business-loans/asset-based-lending", destination: "/financial-services/asset-based-lending", permanent: true },
  { source: "/business-loans/inventory-financing", destination: "/financial-services/asset-based-lending", permanent: true },
  { source: "/business-loans/equipment-financing", destination: "/financial-services/asset-based-lending", permanent: true },
  { source: "/business-loans/commercial-real-estate-loans", destination: "/industries/commercial-construction-financing", permanent: true },
];

// Legacy WordPress industry URLs whose slug differs from the new page. Old
// slugs that already match a current page (e.g. /industries/cpg-financing)
// are intentionally omitted — they resolve directly with no redirect.
const legacyIndustryRedirects = [
  { source: "/industries/distribution-financing", destination: "/industries/distribution-logistics-financing", permanent: true },
  { source: "/industries/service-companies", destination: "/industries/business-services", permanent: true },
  { source: "/industries/medical-financing", destination: "/industries/healthcare-financing", permanent: true },
  { source: "/industries/supply-chain-financing", destination: "/industries/distribution-logistics-financing", permanent: true },
  { source: "/industries/freight-financing", destination: "/industries/transportation-freight-financing", permanent: true },
  { source: "/industries/marine-finance", destination: "/industries/transportation-freight-financing", permanent: true },
  { source: "/industries/staffing-factoring", destination: "/industries/business-services", permanent: true },
  { source: "/industries/commercial-real-estate-financing", destination: "/industries/commercial-construction-financing", permanent: true },
  { source: "/industries/energy-finance", destination: "/industries/energy-infrastructure-financing", permanent: true },
  { source: "/industries/apparel-finance", destination: "/industries/cpg-financing", permanent: true },
  { source: "/industries/telecommunications-financing", destination: "/industries/media-telecommunications-financing", permanent: true },
  { source: "/industries/security-factoring", destination: "/industries/business-services", permanent: true },
  { source: "/industries/janitorial-factoring", destination: "/industries/business-services", permanent: true },
  { source: "/industries/information-technology-factoring", destination: "/industries/technology-financing", permanent: true },
  { source: "/industries/food-and-beverage-financing", destination: "/industries/cpg-financing", permanent: true },
  { source: "/industries/agriculture-financing", destination: "/industries/distribution-logistics-financing", permanent: true },
  { source: "/industries/law-firm-financing", destination: "/industries/business-services", permanent: true },
  { source: "/industries/aviation-financing", destination: "/industries/transportation-freight-financing", permanent: true },
  { source: "/industries/import-export-financing", destination: "/industries/distribution-logistics-financing", permanent: true },
  { source: "/industries/payroll-funding", destination: "/industries/business-services", permanent: true },
  { source: "/industries/construction-invoice-factoring", destination: "/industries/commercial-construction-financing", permanent: true },
  { source: "/industries/logistics-finance", destination: "/industries/distribution-logistics-financing", permanent: true },
  { source: "/industries/hospitality-finance", destination: "/industries/business-services", permanent: true },
];

// Legacy blog-post URLs (renamed slugs and bare /slug paths) → current /blog/slug.
const blogRedirects = [
  { source: "/account-receivable-management-tips", destination: "/blog/account-receivable-management-tips", permanent: true },
  { source: "/accounting-for-factoring-receivables", destination: "/blog/accounting-for-factoring-receivables", permanent: true },
  { source: "/accounts-payable-vs-accounts-receivable", destination: "/blog/accounts-payable-vs-accounts-receivable", permanent: true },
  { source: "/accounts-receivable-automation", destination: "/blog/accounts-receivable-automation", permanent: true },
  { source: "/accounts-receivable-cash-flow", destination: "/blog/accounts-receivable-cash-flow", permanent: true },
  { source: "/accounts-receivable-challenges", destination: "/blog/accounts-receivable-challenges", permanent: true },
  { source: "/accounts-receivable-collection-period", destination: "/blog/accounts-receivable-collection-period", permanent: true },
  { source: "/accounts-receivable-cycle", destination: "/blog/accounts-receivable-cycle", permanent: true },
  { source: "/accounts-receivable-factoring-companies", destination: "/blog/accounts-receivable-factoring-companies", permanent: true },
  { source: "/accounts-receivable-financing", destination: "/blog/accounts-receivable-financing", permanent: true },
  { source: "/accounts-receivable-financing-vs-factoring", destination: "/blog/accounts-receivable-financing-vs-factoring", permanent: true },
  { source: "/accounts-receivable-in-healthcare", destination: "/blog/accounts-receivable-in-healthcare", permanent: true },
  { source: "/accounts-receivable-loans", destination: "/blog/accounts-receivable-loans", permanent: true },
  { source: "/accounts-receivable-process", destination: "/blog/accounts-receivable-process", permanent: true },
  { source: "/accounts-receivable-tracking", destination: "/blog/accounts-receivable-tracking", permanent: true },
  { source: "/accounts-receivables-factoring", destination: "/blog/accounts-receivables-factoring", permanent: true },
  { source: "/alternative-financing", destination: "/blog/alternative-financing", permanent: true },
  { source: "/asset-based-financing", destination: "/blog/asset-based-financing", permanent: true },
  { source: "/asset-based-financing-unleashing-the-power-of-your-assets", destination: "/blog/asset-based-financing-unleashing-the-power-of-your-assets", permanent: true },
  { source: "/asset-based-lending-for-manufacturing-companies", destination: "/blog/asset-based-lending-for-manufacturing-companies", permanent: true },
  { source: "/asset-based-lending-vs-factoring", destination: "/blog/asset-based-lending-vs-factoring", permanent: true },
  { source: "/benefits-of-invoice-factoring", destination: "/blog/benefits-of-invoice-factoring", permanent: true },
  { source: "/best-freight-factoring-companies", destination: "/blog/best-freight-factoring-companies", permanent: true },
  { source: "/best-invoice-factoring-companies", destination: "/blog/best-invoice-factoring-companies", permanent: true },
  { source: "/blog/a-complete-guide-to-understanding-invoice-factoring-examples-across-industries", destination: "/blog/invoice-factoring-example", permanent: true },
  { source: "/blog/accounts-payable-vs-accounts-receivable-understand-the-key-differences", destination: "/blog/accounts-payable-vs-accounts-receivable", permanent: true },
  { source: "/blog/accounts-receivable-financing-vs-factoring-whats-the-difference", destination: "/blog/accounts-receivable-financing-vs-factoring", permanent: true },
  { source: "/blog/advanced-accounting-techniques-for-accounts-receivable-financing", destination: "/blog/accounting-for-factoring-receivables", permanent: true },
  { source: "/blog/asset-based-lending-vs-invoice-factoring-which-is-right-for-your-business", destination: "/blog/asset-based-lending-vs-factoring", permanent: true },
  { source: "/blog/bridge-loans-from-1-million-to-10-million-fast-and-flexible-financing-for-businesses", destination: "/blog/bridge-loans-from-1-million-to-10-million", permanent: true },
  { source: "/blog/how-a-ledgered-line-of-credit-improves-cash-flow-for-growing-businesses", destination: "/blog/ledgered-line-of-credit", permanent: true },
  { source: "/blog/how-accounts-receivable-automation-improves-cash-flow-to-reduce-payment-delays", destination: "/blog/accounts-receivable-automation", permanent: true },
  { source: "/blog/how-accounts-receivable-cycle-impacts-working-capital-and-business-growth", destination: "/blog/accounts-receivable-cycle", permanent: true },
  { source: "/blog/how-accounts-receivable-financing-helps-large-businesses-scale", destination: "/blog/accounts-receivable-financing", permanent: true },
  { source: "/blog/how-accounts-receivable-process-improves-your-working-capital", destination: "/blog/accounts-receivable-process", permanent: true },
  { source: "/blog/how-accounts-receivables-factoring-drives-operational-efficiency", destination: "/blog/accounts-receivables-factoring", permanent: true },
  { source: "/blog/how-asset-based-lending-for-manufacturing-companies-improves-cash-flow-stability", destination: "/blog/asset-based-lending-for-manufacturing-companies", permanent: true },
  { source: "/blog/how-benefit-from-selling-accounts-receivable-for-growth-capital", destination: "/blog/selling-accounts-receivable", permanent: true },
  { source: "/blog/how-businesses-can-use-alternative-financing-to-strengthen-working-capital", destination: "/blog/alternative-financing", permanent: true },
  { source: "/blog/how-does-factoring-work-for-large-enterprises-with-high-invoices", destination: "/blog/how-does-factoring-work", permanent: true },
  { source: "/blog/how-does-supply-chain-finance-work-in-modern-trade-operations", destination: "/blog/how-does-supply-chain-finance-work", permanent: true },
  { source: "/blog/how-import-export-finance-can-improve-cash-flow-in-global-trade", destination: "/blog/import-export-finance", permanent: true },
  { source: "/blog/how-industry-leaders-source-funding-through-government-contract-financing", destination: "/blog/government-contract-financing", permanent: true },
  { source: "/blog/how-inventory-funding-supports-distributors-in-managing-seasonal-demand", destination: "/blog/inventory-funding", permanent: true },
  { source: "/blog/how-large-companies-can-optimize-business-working-capital-for-maximum-efficiency", destination: "/blog/business-working-capital", permanent: true },
  { source: "/blog/how-medical-accounts-receivable-financing-helps-healthcare-providers-manage-cash-flow", destination: "/blog/medical-accounts-receivable-financing", permanent: true },
  { source: "/blog/how-middle-market-companies-optimize-capital-structure-for-sustainable-growth", destination: "/blog/middle-market-companies", permanent: true },
  { source: "/blog/how-private-credit-market-liquidity-helps-ensure-reliable-access-to-corporate-financing", destination: "/blog/pricate-credit-market-liquidity", permanent: true },
  { source: "/blog/how-private-equity-creates-value-in-lower-middle-market-businesses", destination: "/blog/lower-middle-market-private-equity", permanent: true },
  { source: "/blog/how-renewable-energy-finance-is-powering-the-global-green-transition", destination: "/blog/renewable-energy-finance", permanent: true },
  { source: "/blog/how-special-situations-financing-supports-companies-facing-operational-stress", destination: "/blog/special-situations-private-credit", permanent: true },
  { source: "/blog/how-special-situations-fund-supports-companies-facing-operational-stress", destination: "/blog/special-situations-fund", permanent: true },
  { source: "/blog/how-the-accounts-receivable-cash-flow-statement-impacts-financial-forecasting", destination: "/blog/accounts-receivable-cash-flow", permanent: true },
  { source: "/blog/how-the-cost-of-factoring-accounts-receivable-impacts-financial-planning", destination: "/blog/cost-of-factoring-accounts-receivable", permanent: true },
  { source: "/blog/how-to-assess-the-top-accounts-receivable-factoring-companies", destination: "/blog/accounts-receivable-factoring-companies", permanent: true },
  { source: "/blog/how-to-choose-the-best-freight-factoring-companies-for-your-trucking-business", destination: "/blog/best-freight-factoring-companies", permanent: true },
  { source: "/blog/how-to-get-purchase-order-financing-and-avoid-hidden-costs", destination: "/blog/how-to-get-purchase-order-financing", permanent: true },
  { source: "/blog/how-to-improve-cash-flow-in-a-manufacturing-business-for-long-term-success", destination: "/blog/how-to-improve-cash-flow-in-a-manufacturing-business", permanent: true },
  { source: "/blog/how-to-prepare-your-invoice-to-meet-factoring-requirements", destination: "/blog/invoice-factoring-requirements", permanent: true },
  { source: "/blog/how-to-secure-government-purchase-order-financing-for-contractors", destination: "/blog/government-purchase-order-financing", permanent: true },
  { source: "/blog/invoice-factoring-guide-how-it-works-and-why-businesses-need-it", destination: "/blog/invoice-factoring-guide", permanent: true },
  { source: "/blog/invoice-financing-vs-factoring-key-differences-every-business-should-know", destination: "/blog/invoic-financing-vs-factoring", permanent: true },
  { source: "/blog/is-a-purchase-order-a-contract-in-business-transactions", destination: "/blog/is-a-purchase-order-a-contract", permanent: true },
  { source: "/blog/is-accounts-receivable-an-asset-understand-its-role-in-businesses", destination: "/blog/is-accounts-receivable-an-asset", permanent: true },
  { source: "/blog/is-an-invoice-a-legal-document-a-comprehensive-guide-for-businesses", destination: "/blog/is-an-invoice-a-legal-document", permanent: true },
  { source: "/blog/key-benefits-of-middle-market-lending-every-business-should-know", destination: "/blog/middle-market-lending", permanent: true },
  { source: "/blog/ledger-balance-vs-available-balance-understand-key-differences", destination: "/blog/ledger-balance-vs-available-balance", permanent: true },
  { source: "/blog/lower-middle-market-private-equity-2", destination: "/blog/middle-market-private-credit", permanent: true },
  { source: "/blog/private-credit-in-2026-opportunity-or-emerging-risk-for-middle-market-borrowers", destination: "/blog/private-credit-risks", permanent: true },
  { source: "/blog/private-credit-lending-how-non-bank-capital-is-powering-business-growth", destination: "/blog/private-credit-lending", permanent: true },
  { source: "/blog/the-pros-and-cons-of-accounts-receivable-loans-is-it-right-for-you", destination: "/blog/accounts-receivable-loans", permanent: true },
  { source: "/blog/the-role-of-factoring-for-government-contracts-in-supporting-manufacturing-growth", destination: "/blog/factoring-for-government-contracts", permanent: true },
  { source: "/blog/the-role-of-ledger-in-accounting-for-smart-financing-decisions", destination: "/blog/ledger-in-accounting", permanent: true },
  { source: "/blog/the-role-of-private-capital-in-financing-oil-and-gas-projects", destination: "/blog/financing-oil-and-gas-projects", permanent: true },
  { source: "/blog/the-strategic-role-of-liquidity-in-middle-market-corporate-finance", destination: "/blog/middle-market-corporate-finance", permanent: true },
  { source: "/blog/top-10-benefits-of-invoice-factoring-for-growing-businesses", destination: "/blog/benefits-of-invoice-factoring", permanent: true },
  { source: "/blog/top-accounts-receivable-challenges-and-how-to-overcome-them", destination: "/blog/accounts-receivable-challenges", permanent: true },
  { source: "/blog/top-features-to-look-for-in-the-best-invoice-factoring-companies", destination: "/blog/best-invoice-factoring-companies", permanent: true },
  { source: "/blog/top-hotel-financing-options-every-hospitality-investor-should-know", destination: "/blog/hotel-financing", permanent: true },
  { source: "/blog/top-industries-with-the-longest-accounts-receivable-collection-periods", destination: "/blog/accounts-receivable-collection-period", permanent: true },
  { source: "/blog/top-rated-international-factoring-companies-leading-the-global-financial-landscape", destination: "/blog/international-factoring-companies", permanent: true },
  { source: "/blog/ucc-filing-meaning-and-how-a-lien-can-limit-your-access-to-financing", destination: "/blog/ucc-filing-meaning", permanent: true },
  { source: "/blog/understand-pros-and-cons-of-purchase-order-financing-before-you-apply", destination: "/blog/purchase-order-financing-pros-and-cons", permanent: true },
  { source: "/blog/understand-the-risks-and-rewards-of-asset-based-financing", destination: "/blog/asset-based-financing", permanent: true },
  { source: "/blog/what-are-middle-market-business-loans-and-how-do-they-work", destination: "/blog/middle-market-loans", permanent: true },
  { source: "/blog/what-does-payment-deferred-mean-and-how-does-it-work-for-businesses", destination: "/blog/what-does-payment-deferred-mean", permanent: true },
  { source: "/blog/what-is-a-factoring-company-and-is-it-right-for-your-industry", destination: "/blog/what-is-a-factoring-company", permanent: true },
  { source: "/blog/what-is-a-letter-of-credit-how-businesses-use-it-to-secure-trade-finance", destination: "/blog/letter-of-credit", permanent: true },
  { source: "/blog/what-is-a-notice-of-assignment-noa-in-factoring-and-why-does-it-matter", destination: "/blog/notice-of-assignment-factoring", permanent: true },
  { source: "/blog/what-is-accounts-receivable-financing-a-strategic-solution-for-industries-like-manufacturing-and-oil-gas", destination: "/blog/what-is-accounts-receivable-financing", permanent: true },
  { source: "/blog/what-is-accounts-receivable-in-healthcare-and-how-can-you-improve-it", destination: "/blog/accounts-receivable-in-healthcare", permanent: true },
  { source: "/blog/what-is-fpa-a-complete-guide-to-financial-planning-and-analysis", destination: "/blog/what-is-fp-and-a", permanent: true },
  { source: "/blog/what-is-non-recourse-factoring-and-how-does-it-work", destination: "/blog/what-is-non-recourse-factoring", permanent: true },
  { source: "/blog/what-is-the-real-cost-of-invoice-factoring-and-how-are-rates-calculated", destination: "/blog/invoice-factoring-rates", permanent: true },
  { source: "/blog/what-makes-a-successful-international-purchase-order-financing", destination: "/blog/international-purchase-order-financing", permanent: true },
  { source: "/blog/why-accurate-accounts-receivable-tracking-matters-for-growing-businesses", destination: "/blog/accounts-receivable-tracking", permanent: true },
  { source: "/blog/why-do-factoring-companies-buy-accounts-receivable-and-how-does-it-help-your-business", destination: "/blog/buy-accounts-receivable", permanent: true },
  { source: "/blog/why-purchase-order-finance-is-a-game-changer-for-apparel-brands-scaling-rapidly", destination: "/blog/purchase-order-finance-apparel", permanent: true },
  { source: "/blog/why-use-purchase-order-financing-for-import-business", destination: "/blog/import-purchase-order-financing", permanent: true },
  { source: "/bridge-loans-from-1-million-to-10-million", destination: "/blog/bridge-loans-from-1-million-to-10-million", permanent: true },
  { source: "/business-working-capital", destination: "/blog/business-working-capital", permanent: true },
  { source: "/buy-accounts-receivable", destination: "/blog/buy-accounts-receivable", permanent: true },
  { source: "/commercial-finance-unleashing-the-power-of-capital-for-business-growth", destination: "/blog/commercial-finance-unleashing-the-power-of-capital-for-business-growth", permanent: true },
  { source: "/cost-of-factoring-accounts-receivable", destination: "/blog/cost-of-factoring-accounts-receivable", permanent: true },
  { source: "/factoring-for-government-contracts", destination: "/blog/factoring-for-government-contracts", permanent: true },
  { source: "/financing-oil-and-gas-projects", destination: "/blog/financing-oil-and-gas-projects", permanent: true },
  { source: "/government-contract-financing", destination: "/blog/government-contract-financing", permanent: true },
  { source: "/government-purchase-order-financing", destination: "/blog/government-purchase-order-financing", permanent: true },
  { source: "/hotel-financing", destination: "/blog/hotel-financing", permanent: true },
  { source: "/how-does-factoring-work", destination: "/blog/how-does-factoring-work", permanent: true },
  { source: "/how-does-supply-chain-finance-work", destination: "/blog/how-does-supply-chain-finance-work", permanent: true },
  { source: "/how-to-get-purchase-order-financing", destination: "/blog/how-to-get-purchase-order-financing", permanent: true },
  { source: "/how-to-improve-cash-flow-in-a-manufacturing-business", destination: "/blog/how-to-improve-cash-flow-in-a-manufacturing-business", permanent: true },
  { source: "/how-to-start-operate-and-scale-a-commercial-cleaning-business-5", destination: "/blog/commercial-finance-unleashing-the-power-of-capital-for-business-growth", permanent: true },
  { source: "/how-to-start-operate-and-scale-a-commercial-cleaning-business-6", destination: "/blog/unlocking-business-cash-flow-an-introduction-to-accounts-receivable-financing", permanent: true },
  { source: "/how-to-start-operate-and-scale-a-commercial-cleaning-business-7", destination: "/blog/asset-based-financing-unleashing-the-power-of-your-assets", permanent: true },
  { source: "/import-export-finance", destination: "/blog/import-export-finance", permanent: true },
  { source: "/import-purchase-order-financing", destination: "/blog/import-purchase-order-financing", permanent: true },
  { source: "/international-factoring-companies", destination: "/blog/international-factoring-companies", permanent: true },
  { source: "/international-purchase-order-financing", destination: "/blog/international-purchase-order-financing", permanent: true },
  { source: "/inventory-funding", destination: "/blog/inventory-funding", permanent: true },
  { source: "/invoic-financing-vs-factoring", destination: "/blog/invoic-financing-vs-factoring", permanent: true },
  { source: "/invoice-factoring-example", destination: "/blog/invoice-factoring-example", permanent: true },
  { source: "/invoice-factoring-guide", destination: "/blog/invoice-factoring-guide", permanent: true },
  { source: "/invoice-factoring-rates", destination: "/blog/invoice-factoring-rates", permanent: true },
  { source: "/invoice-factoring-requirements", destination: "/blog/invoice-factoring-requirements", permanent: true },
  { source: "/invoice-factoring-vs-reverse-factoring-how-to-choose-the-right-option-for-your-company", destination: "/blog/invoice-factoring-vs-reverse-factoring-how-to-choose-the-right-option-for-your-company", permanent: true },
  { source: "/is-a-purchase-order-a-contract", destination: "/blog/is-a-purchase-order-a-contract", permanent: true },
  { source: "/is-accounts-receivable-an-asset", destination: "/blog/is-accounts-receivable-an-asset", permanent: true },
  { source: "/is-an-invoice-a-legal-document", destination: "/blog/is-an-invoice-a-legal-document", permanent: true },
  { source: "/large-business-loans", destination: "/blog/large-business-loans", permanent: true },
  { source: "/ledger-balance-vs-available-balance", destination: "/blog/ledger-balance-vs-available-balance", permanent: true },
  { source: "/ledger-in-accounting", destination: "/blog/ledger-in-accounting", permanent: true },
  { source: "/ledgered-line-of-credit", destination: "/blog/ledgered-line-of-credit", permanent: true },
  { source: "/letter-of-credit", destination: "/blog/letter-of-credit", permanent: true },
  { source: "/lower-middle-market-private-equity", destination: "/blog/lower-middle-market-private-equity", permanent: true },
  { source: "/medical-accounts-receivable-financing", destination: "/blog/medical-accounts-receivable-financing", permanent: true },
  { source: "/middle-market-companies", destination: "/blog/middle-market-companies", permanent: true },
  { source: "/middle-market-corporate-finance", destination: "/blog/middle-market-corporate-finance", permanent: true },
  { source: "/middle-market-lending", destination: "/blog/middle-market-lending", permanent: true },
  { source: "/middle-market-loans", destination: "/blog/middle-market-loans", permanent: true },
  { source: "/middle-market-private-credit", destination: "/blog/middle-market-private-credit", permanent: true },
  { source: "/notice-of-assignment-factoring", destination: "/blog/notice-of-assignment-factoring", permanent: true },
  { source: "/post-5", destination: "/blog/commercial-finance-unleashing-the-power-of-capital-for-business-growth", permanent: true },
  { source: "/post-6", destination: "/blog/unlocking-business-cash-flow-an-introduction-to-accounts-receivable-financing", permanent: true },
  { source: "/post-7", destination: "/blog/asset-based-financing-unleashing-the-power-of-your-assets", permanent: true },
  { source: "/pricate-credit-market-liquidity", destination: "/blog/pricate-credit-market-liquidity", permanent: true },
  { source: "/private-credit-lending", destination: "/blog/private-credit-lending", permanent: true },
  { source: "/private-credit-risks", destination: "/blog/private-credit-risks", permanent: true },
  { source: "/purchase-order-finance-apparel", destination: "/blog/purchase-order-finance-apparel", permanent: true },
  { source: "/purchase-order-financing-pros-and-cons", destination: "/blog/purchase-order-financing-pros-and-cons", permanent: true },
  { source: "/receivables-financing-vs-factoring", destination: "/blog/receivables-financing-vs-factoring", permanent: true },
  { source: "/renewable-energy-finance", destination: "/blog/renewable-energy-finance", permanent: true },
  { source: "/selling-accounts-receivable", destination: "/blog/selling-accounts-receivable", permanent: true },
  { source: "/special-situations-fund", destination: "/blog/special-situations-fund", permanent: true },
  { source: "/special-situations-private-credit", destination: "/blog/special-situations-private-credit", permanent: true },
  { source: "/ucc-filing-meaning", destination: "/blog/ucc-filing-meaning", permanent: true },
  { source: "/unlocking-business-cash-flow-an-introduction-to-accounts-receivable-financing", destination: "/blog/unlocking-business-cash-flow-an-introduction-to-accounts-receivable-financing", permanent: true },
  { source: "/what-does-payment-deferred-mean", destination: "/blog/what-does-payment-deferred-mean", permanent: true },
  { source: "/what-is-a-factoring-company", destination: "/blog/what-is-a-factoring-company", permanent: true },
  { source: "/what-is-accounts-receivable-financing", destination: "/blog/what-is-accounts-receivable-financing", permanent: true },
  { source: "/what-is-fp-and-a", destination: "/blog/what-is-fp-and-a", permanent: true },
  { source: "/what-is-non-recourse-factoring", destination: "/blog/what-is-non-recourse-factoring", permanent: true },
];

const nextConfig = {
  devIndicators: false,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
      },
    ],
  },
  async redirects() {
    return [
      ...pageRedirects,
      ...structureRedirects,
      ...legacyServiceRedirects,
      ...legacyIndustryRedirects,
      ...blogRedirects,
    ];
  },
};

module.exports = nextConfig;
